### ISSUE TITLE
Cant Load Ext page for set configuration

### ISSUE THREAD

**Issue by pMonfared** [plesk/ext-pagespeed-insights#1]
![image](https://cloud.githubusercontent.com/assets/10448255/24297000/e1373c5c-10be-11e7-86eb-1880fc1398fb.png)

**Comment by Kubik-Rubik** [comment]
@pMonfared Hi! Is this issue still valid? I cannot reproduce it with several test environments. Please try again!

**Comment by Kubik-Rubik** [comment]
I will close here because it is not related to the PageSpeed Insights extension. Thanks!
