### ISSUE TITLE
Unable to Connect: Connection timed out

### ISSUE THREAD

**Issue by Xenocide122** [plesk/ext-pagespeed-insights#5]
Getting the following error (running v1.1.0) when trying to analyze any of my sites:

Unable to Connect to ssl://www.googleapis.com:443. Error #110: Connection timed out

**Comment by Kubik-Rubik** [comment]
This bug was fixed in the latest version (2.0.0): https://ext.plesk.com/packages/3d2639e6-64a9-43fe-a990-c873b6b3ec66-pagespeed-insights
