### ISSUE TITLE
Unable to download optimized image, JavaScript, and CSS resources

### ISSUE THREAD

**Issue by vlikhtanskiy** [plesk/ext-pagespeed-insights#6]
Original report: https://talk.plesk.com/threads/extension-google-pagespeed-insights-issue.345160/

using this extension in the domain page we got the link:

Download optimized image, JavaScript, and CSS resources for this page.

which points to: https://developers.google.com/speed/pagespeed/insights/optimizeContents?url=http://DOMAIN.TLD&strategy=desktop

but clicking it we got error from Google API:

The referrer https://OURPLESKSERVERNAME:8443/modules/pagespeed-insights/index.php/index/result?dom_id=5&site_id=5 does not match the referrer restrictions configured on your API key. Please use the API Console to update your key restrictions.

I swapped urls for privacy reasons.

**Comment by Kubik-Rubik** [comment]
This bug was fixed in the latest release (2.0.0): https://ext.plesk.com/packages/3d2639e6-64a9-43fe-a990-c873b6b3ec66-pagespeed-insights
