### ISSUE TITLE
Unable to Connect to ssl://www.googleapis.com:443. Error 0 on Windows

### ISSUE THREAD

**Issue by xgin** [plesk/ext-pagespeed-insights#8]
Plesk for Windows before 17.8 does not ship CA bundle.
The extension fails to connect to the API via SSL.

**Comment by Kubik-Rubik** [comment]
This bug was fixed in the latest version (2.0.0): https://ext.plesk.com/packages/3d2639e6-64a9-43fe-a990-c873b6b3ec66-pagespeed-insights
